myapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'myapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('delete/<city_name>/', views.delete_city, name='delete_city'),
    path('users/<int:pk>', views.users_detail, name='users_detail'),
    path('photos/new/', views.photos_new, name='photos_new'),
    path('photos/<int:pk>/', views.photos_detail, name='photos_detail'),
    path('photos/<int:pk>/delete/', views.photos_delete, name='photos_delete'),
    path('photos/<int:pk>/edit/', views.edit, name='edit'),
    path('photos/<str:category>/', views.photos_category, name='photos_category'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='myapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth import get_user_model


class City(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'cities'


class Category(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title


class Photo(models.Model):
    title = models.CharField(max_length=50)
    comment = models.TextField(blank=True)
    image = models.ImageField(upload_to='photos')
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)

myapp/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm, TextInput
from .models import Photo, City


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class PhotoForm(ModelForm):
    class Meta:
        model = Photo
        fields = ['title', 'comment', 'image', 'category']


class CityForm(ModelForm):
    class Meta:
        model = City
        fields = ['name']
        widgets = {'name': TextInput(attrs={'class': 'input', 'placeholder': 'City Name'})}

myapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, get_user_model
from .forms import CustomUserCreationForm, PhotoForm, CityForm
from .models import Photo, Category, City
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.http import require_POST
import requests
import json



def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            input_username = form.cleaned_data['username']
            input_email = form.cleaned_data['email']
            input_password = form.cleaned_data['password1']
            new_user = authenticate(email=input_email, password=input_password)

            if new_user is not None:
                login(request, new_user)
                return redirect('myapp:index')
    else:
        form = CustomUserCreationForm()
    return render(request, 'myapp/signup.html', {'form': form})


def index(request):
    photos = Photo.objects.all().order_by('-created_at')
    url = 'http://api.openweathermap.org/data/2.5/weather?units=metric&q={}&units=imperial&appid=f448c72be27bc84a6cfbbb669228e298'

    err_msg = ''
    message = ''
    message_class = ''

    if request.method == 'POST':
        form = CityForm(request.POST)
        
        if form.is_valid():
            new_city = form.cleaned_data['name'].lower()
            existing_city_count = City.objects.filter(name=new_city).count()

            if existing_city_count == 0:
                r = requests.get(url.format(new_city)).json()

                if r['cod'] == 200:
                    form.save()
                else:
                    err_msg = 'City does not exist in the world!'
            else:
                err_msg = 'City already exists in the database!'
        

        if err_msg:
            message = err_msg
            message_class = 'alert-danger'
        else:
            message = 'City added succenssfully!'
            message_class = 'alert-info'

    form = CityForm()
    cities = City.objects.all()

    weather_data = []

    for city in cities:
        r = requests.get(url.format(city)).json()

        city_weather = {
            'city': city.name,
            'temperature': r['main']['temp'],
            'description': r['weather'][0]['description'],
            'icon': r['weather'][0]['icon'],
        }

        weather_data.append(city_weather)

    
    context = {
        'weather_data': weather_data,
        'form': form,
        'message': message,
        'message_class': message_class,
        'photos': photos,
    }
    return render(request, 'myapp/index.html', context)


def delete_city(request, city_name):
    City.objects.get(name=city_name).delete()
    return redirect('myapp:index')



def users_detail(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    photos = user.photo_set.all().order_by('-created_at')
    return render(request, 'myapp/users_detail.html', {'user': user, 'photos': photos})


@login_required
def photos_new(request):
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            photo = form.save(commit=False)
            photo.user = request.user
            photo.save()
            messages.success(request, '投稿が完了しました！')
        return redirect('myapp:users_detail', pk=request.user.pk)
    else:
        form = PhotoForm()
    return render(request, 'myapp/photos_new.html', {'form':form})


def photos_detail(request, pk):
    photo = get_object_or_404(Photo, pk=pk)


    return render(request, 'myapp/photos_detail.html', {'photo': photo})


@require_POST
def photos_delete(request, pk):
    photo = get_object_or_404(Photo, pk=pk)
    photo.delete()
    return redirect('myapp:users_detail', request.user.id)


@login_required
def edit(request, pk):
    photo = get_object_or_404(Photo, pk=pk)
    if request.method == 'POST':
        form = PhotoForm(request.POST,request.FILES, instance=photo)
        if form.is_valid():
            form.save()
            return redirect('myapp:photos_detail', pk=pk)
    else:
        form = PhotoForm(instance=photo)
    context = {'form': form, 'photo': photo}
    return render(request, 'myapp/edit.html', context)


def photos_category(request, category):
    # titleがURLの文字列と一致するCategoryインスタンスを取得
    category = Category.objects.get(title=category)
    # 取得したCategoryに属するPhoto一覧を取得
    photos = Photo.objects.filter(category=category).order_by('-created_at')
    return render(request, 'myapp/index.html', {'photos': photos, 'category': category})

myapp/templates/myapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>rider SNS</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
    <link rel="stylesheet" type='text/css' href="{% static 'css/style.css' %}">
    
  </head>

  <body>
    <header class='fixed-top'>
      <nav class='navbar navbar-expand-lg navbar-light navbar-dark bg-dark'>
        <a class='navbar-brand' href="{% url 'myapp:index' %}">Riders</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id='navbarNav'>
          <ul class='navbar-nav'>
            <li class='nav-item active'>
              <a class='nav-link' href="{% url 'myapp:photos_new' %}">投稿</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class='nav-item active'>
              <a class='nav-link' href="{% url 'myapp:users_detail' request.user.id %}">マイページ</a>
            </li>
            <li class='nav-item active'>
              <a class='nav-link' href="{% url 'myapp:logout' %}">ログアウト</a>
            </li>
            {% else %}
            <li class='nav-item active'>
              <a class='nav-link' href="{% url 'myapp:login' %}">ログイン</a>
            </li>
            <li class='nav-item active'>
              <a class='nav-link' href="{% url 'myapp:signup' %}">新規登録</a>
            </li>
            {% endif %}
            <li class='nav-item active'>
              <a class='nav-link' href="#"></a>
            </li>
            <li class='nav-item active'>
              <a class='nav-link' href="#"></a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    
    <div class="container mt-5">
      {% for message in messages %}
          <p class='alert alert-success'>{{ message }}</p>
      {% endfor %}
      {% block content %}{% endblock %}
    </div>




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

myapp/templates/myapp/edit.html
{% extends 'myapp/base.html' %}


{% block content %}

<div>
    <a href="{% url 'myapp:index' %}">ホームに戻る</a>
  </div>
  <form action="{% url 'myapp:edit' photo.id %}" method="post" enctype='multipart/form-data'>
  {% csrf_token %}
    <table>
      <div class='mt-3'>
      <tr>
        <th>タイトル</th>
        <td>{{ form.title }}</td>
      </tr>
    </div>
    <div>
      <tr>
        <th>コメント</th>
        <td>{{ form.comment }}</td>
      </tr>
    </div>
      <tr>
        <th>画像</th>
        <td>{{ form.image }}</td>
      </tr>
      <tr>
        <th>カテゴリー</th>
        <td>{{ form.category }}</td>
      </tr>
    </table>
    <button type="submit" class="btn alert-primary">保存</button>
  </form>


{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}



{% block content %}
{% if request.user.is_authenticated %}
<section class='section'>
        <div class='columns'>
            <div class='column is-offset-4 is-4'>
                <form method="POST">
                    {% csrf_token %}
                    <div class='field has-addons'>
                        <div class='control is-expanded'>
                            {{ form.name }}
                        </div>
                        <div class='control'>
                            <button type='submit' class='button is-info'>
                                Add City
                            </button>
                        </div>
                    </div>
                    {% if message %}
                    <div class="alert {{ message_class }}">{{ message }}</div>
                    {% endif %}
                </form>
            </div>
        </div>
</section>
{% endif %}
<section class='section'>
            <div class='columns'>
                {% for city_weather in weather_data %}
                <div class='box mr-5'>
                    <article class='media'>
                            <figure class='image is-50×50'>
                                <img src="http://openweathermap.org/img/w/{{ city_weather.icon }}.png" alt="Image">
                            </figure>
                        <div class='media-content'>
                            <div class='content'>
                                <p>
                                    <span class='title'>{{ city_weather.city }}</span>
                                    <br>
                                    <span class='subtitle'>{{ city_weather.temperature }} °C</span>
                                    <br> {{ city_weather.description }}
                                </p>
                            </div>
                        </div>
                        {% if request.user.is_authenticated %}
                        <div class='media-right'>
                            <a href="{% url 'myapp:delete_city' city_weather.city %}">
                                <button class='delete'></button>
                            </a>
                        </div>
                        {% endif %}
                    </article>
                </div>
                {% endfor %}
        </div>
</section>

{% if category %}
    <h2>カテゴリー：{{ category.title }}の検索結果</h2>
{% endif %}


{% include 'myapp/photos_list.html' %}

{% endblock %}

myapp/templates/myapp/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>rider SNS</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body class="text-center">
    <div class="container">
      <form class="form-signin" method='POST'>
        {% csrf_token %}
        <img class="mb-4" src="/docs/4.4/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
        {% if form.errors %}
            <p>メールアドレスかパスワードが間違っています。</p>
        {% endif %}
        <h1 class="h3 mb-3 font-weight-normal">Please log in</h1>
        <label for="inputEmail" >Email address</label><br>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus name='username'>
        <label for="inputPassword">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required name='password'>
        <p></p>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
      </form>
    </div>
</body>
</html>

myapp/templates/myapp/photos_detail.html
{% extends 'myapp/base.html' %}

{% block content %}

<div class="photo-detail">
<img src="{{ photo.image.url }}" class="photo-img mt-5">
  <div class="photo-info mt-3">
    <a href="{% url 'myapp:users_detail' photo.user.id %}">@{{ photo.user.username }}</a>
  </div>
  <div class='mt-2 mb-3'>
      <h1>{{ photo.title }}</h1>
  </div>
  <div class="mb-5">
      <p>{{ photo.comment }}</p>
  </div>
  <!-- 削除ボタン -->
  {% if request.user == photo.user %}
  <form action="{% url 'myapp:edit' photo.id %}">
    <button class="btn alert-primary" style='float:left; margin-right: 7px; '>編集</button>
  </form>
  <form action="{% url 'myapp:photos_delete' photo.id %}" method="post" >{% csrf_token %}
    <button class='btn alert-secondary' type="submit" onclick='return confirm("本当に削除しますか？");'>削除</button>
  </form>
  
  {% endif %}


</div>


{% endblock %}

myapp/templates/myapp/photos_list.html
<div class='photo-container'>
    {% for photo in photos %}
        <div class='photo'>
            <a href="{% url 'myapp:photos_detail' photo.id %}">
                <img src="{{ photo.image.url }}" alt="some errors occur!" class='photo-img'>
            </a>
            <div class='photo-info'>
                <a href="{% url 'myapp:photos_category' category=photo.category %}" class='category'>{{ photo.category }}</a>
                <a href="{% url 'myapp:users_detail' photo.user.id %}">@{{ photo.user.username }}</a>
                </p>
            </div>
        </div>
    {% endfor %}
</div>

myapp/templates/myapp/photos_new.html
{% extends 'myapp/base.html' %}


{% block content %}

<div>
  <a href="{% url 'myapp:index' %}">ホームに戻る</a>
</div>
<form action="{% url 'myapp:photos_new' %}" method="post" enctype='multipart/form-data'>
{% csrf_token %}
  <table>
    <div class='mt-3'>
    <tr>
      <th>タイトル</th>
      <td>{{ form.title }}</td>
    </tr>
  </div>
  <div>
    <tr>
      <th>コメント</th>
      <td>{{ form.comment }}</td>
    </tr>
  </div>
    <tr>
      <th>画像</th>
      <td>{{ form.image }}</td>
    </tr>
    <tr>
      <th>カテゴリー</th>
      <td>{{ form.category }}</td>
    </tr>
  </table>
  <button type="submit" class="btn alert-primary">保存</button>
</form>


{% endblock %}

myapp/templates/myapp/signup.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>rider SNS</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body class="text-center">
    <div class="container">
      <form method='POST' action="{% url 'myapp:signup' %}">
        {% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal">Please Sign up</h1>
        <label>Username</label>
        {{ form.username }}
        {{ form.username.errors }}
        <br>
        <label>Email address</label>
        {{ form.email }}
        {{ form.email.errors }}
        <br>
        <label>Password</label>
        {{ form.password1 }}
        {{ form.password1.errors }}
        <br>
        <label>Confirm Password</label>
        {{ form.password2 }}
        {{ form.password2.errors }}
        <br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Signup</button>
      </form>
    </div>
</body>
</html>

myapp/templates/myapp/users_detail.html
{% extends 'myapp/base.html' %}

{% block content %}

<h2 class='user-name'>@{{ user.username }}</h2>

{% if photos.count != 0 %}
    <p>投稿<strong>{{ photos.count }}</strong>件</p>
{% else %}
    {% if user == request.user %}
        <p>初めての投稿をしてみましょう！</p>
    {% else %}
        <p>@{{ user.username }}さんはまだ投稿していません。</p>
    {% endif %}
{% endif %}


{% include 'myapp/photos_list.html' %}

{% endblock %}